use_frameworks!

target 'learnReactiveSwift' do
#    pod 'SQLite.swift', '~> 0.11.3'
    pod "AwesomeCache", "~> 5.0"
    pod 'Alamofire'
    pod 'Kingfisher', '~> 3.13.1'
    pod 'Dollar'
    pod 'Curry'
    pod 'Alamofire'
    pod 'Argo'
    pod 'Curry'
    pod 'ReactiveCocoa'
    pod 'ReactiveSwift'
    pod 'Delta', :git => "https://github.com/thoughtbot/Delta.git"
end
